version: "2"

output:
  sort-results: true
  print-issued-lines: false

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - nolintlint
    - revive
    # gofumpt is not available as a linter in golangci-lint v2+
    # it can be run separately as a formatter gpfumpt -w .

linters-settings:
  govet:
    enable:
      - nilness
      - reflectvaluecompare
      - sortslice
      - unusedwrite

  errcheck:
    check-type-assertions: true

  revive:
    ignoreFileHeader: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false

  exclude-rules:
    - linters: [revive]
      text: 'unused-parameter: parameter \S+ seems to be unused, consider removing or renaming it as _'
    - linters: [revive]
      text: 'empty-block: this block is empty, you can remove it'
    - linters: [revive]
      path: time.go
      text: 'blank-imports'
