version: "2"

linters:
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - revive
    - misspell
    # gofumpt is a slightly stricter formatter than gofmt
    - gofumpt

linters-settings:
  errcheck:
    check-type-assertions: true
  misspell:
    locale: US
  gofumpt:
    extra-rules: true
  revive:
    rules:
      # we use a blank import of unsafe in time.go
      # to access runtime.nanotime for monotonic time measures.
      # we disable this rule here for the false positive.
      -name: blank-imports
       disabled: true

run:
  timeout: 2m
  tests: true
