version: "2"

linters:
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - revive
    - misspell
    - gofumpt # a bit of a stricter formatter

linters-settings:
  errcheck:
    check-type-assertions: true
  misspell:
    locale: US
  gofumpt:
    extra-rules: true

run:
  timeout: 2m
  tests: true
